spring:
  profiles:
    active: dev #默认为开发环境

  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /his
    username: his
    password: his
    publisher-confirms: true #如果对异步消息需要回调必须设置为true

  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: Password123@redis # Redis服务器连接密码（默认为空）
    #url: redis://file@localhost:6380
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）


server:
  port: 8073

#mybatis:
#  mapper-locations:classpath:com/neu/his/sms/com.neu.his.sms.mapper/*.xml,classpath:com/neu/his/mbg/mapper/*.xml

casdoor:
  endpoint: http://172.21.16.11:8091
  client-id: a07d0ddd8eaee128d94c
  client-secret: ae3532cf4dd98256cb72a234995022cd15f10113
  jwt-public-key: \
  -----BEGIN CERTIFICATE-----\n\
  MIIE2TCCAsGgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCYxDjAMBgNVBAoTBWFk\n\
  bWluMRQwEgYDVQQDDAtjZXJ0X2VlenFoOTAeFw0yMjA0MjgwODI5MjVaFw00MjA0\n\
  MjgwODI5MjVaMCYxDjAMBgNVBAoTBWFkbWluMRQwEgYDVQQDDAtjZXJ0X2VlenFo\n\
  OTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMQYvfuWxGtvcb3rfvvR\n\
  DQhT6WZKxH57NYAsKAyNlpWNza3bS7I85t+HQo9aV7POYkr98v5NJ/rQg0piOzpj\n\
  mqf3Ndom0jm0ZiHRjiK5pGlWXkYbBNPnYHRNCx5npWoLvfzu7tKJnsBqMEWY5M5v\n\
  rTrhAigS5qWSl6sT/h5DZJy2AUtCjV5Q4zOUIFDoqbPtP59ScX2c+UrAi0yoiCTK\n\
  XbANQjhso+arglLwG0cg0NCztUcjmLfbB4M3fsOKN0LYbQEn7UNpMWM6fl/X+r6t\n\
  L/qjWMnyun0VcHucb2da73zRxuPA5gVkRvxEGRTxL7qFyqU0Xrdj7qRZJucv3VGg\n\
  cOTzUvICTrHSXKegkt4DQPp2tk/h9+0yI4ia0all1imiIGvoPYo6eB74YLZwfYv9\n\
  LkYSnjj3rhbXQLltN2UqkBO9KLu8FOD+/TtXbjdgIUEpcNE6m5tvwFCGLa7dfUMp\n\
  PzogoAPOqsJmjf+t8Sa5p57eCdCX4kXCHyWbN+cqLaRP3W8FvsdKA8MOpiZhMynA\n\
  e3o0euNsHPTZfzv+qZaFjYy7RnKWHe7VXiCQqaD6RGsl4Oq1raGkO26cKY6eSLFe\n\
  9X5HU6ykQYWVUEjc1pwol9Yix6oJOVIhN+NQSjHU0vF/OBKm3eWBsNB0pIeAgJi5\n\
  Casdm5JCabpO+8E4Et2ijtNzAgMBAAGjEDAOMAwGA1UdEwEB/wQCMAAwDQYJKoZI\n\
  hvcNAQELBQADggIBAMORDKcScl5I1MzTaq8lFiCNrG/F58bavkzUY/7rff+MFKMl\n\
  thO/NfsKvPehY4+nowHxKbB9+q3ZDpEz5/UXIHns/u8tl4AuVXcYZRhaF6UE1jeD\n\
  V3h0B0CmHYOa0j9xaxqNL3VVL8lmzN4h3vY8N5j81wqKHxncNqDW8u4UA7uP4OFN\n\
  G/z8ckBHzq61orRunhfCQc/016ORQ8XMCwVGhC1i5tfGDxhOQqSMaz5KAoZCukgb\n\
  OrJ8On3h7Y1U+MEjL/llcYK7mnupKmxzYwwFSfXbw8N81Fvo4ZPiY7zc8x3hGPAQ\n\
  fKHFerTrnVRXtJM0XS9uW5+C/2ne3jRf3LEc1RgNwFtkz4aFouSsWyvBn/gfykEk\n\
  QnZgpK3NDChm+rXs+SzOABME1QKYwsahxrD8aLHvfNYueGnKlibn8B4QqzGURrQu\n\
  AB/1hSRXH/xtPTs85MxOlnUhsQTCahAfYcszlDoB3Jm/n8yEsOtFDd5o+g0EZ0EC\n\
  0K4nEK8HRLuoxdnQPew7uE8ra6Fv29X+7s1noVgf+MeFwup2K3q0EwP/slXjUGid\n\
  VgLIBr2NUvC8M3yBWcfqpA91fKGXO9YNeBzt2Hy0kbNW0c5dOx6+KX3xf6sP30Yt\n\
  aWh7tM4YAPXIMCwqlSZzf0smsVPsb9NhLVPNJmVuSASq1R7klsQIQDiaokyK\n\
  -----END CERTIFICATE-----
  organization-name: built-in
  application-name: application_his

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI6jw7P8XVANMr
    accessKeySecret: CA377oINCgB7gppTQoKdFoIim8rIVF
    bucketName: zain-images
    policy:
      expire: 300
    maxSize: 10
    callback: http://localhost:8080/aliyun/oss/callback
    dir:
      prefix: mall/images/

logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.neu.his: debug
#  file: E:/log #配置日志文件路径
#  path: demo_log.log #配置日志生成名称

